### ISSUE TITLE
Error getting region from cookie when another cookie value is set

### ISSUE THREAD

**Issue by furmandev** [bricefrisco/NamesLoL-Frontend-Old#1]
Hello! Love the project! I will definitely make use of it myself. Anyways, I encountered a small issue. 

I have a chrome extention called [Auto Refresh Plus](https://chrome.google.com/webstore/detail/auto-refresh-plus-page-mo/hgeljhfekpckiiplhkigfehkdpldcggm?hl=en). Apparently, this extension adds a key to the document cookie, which caused `parseRegion` to return an invalid value, which the back-end didn't like:

![image](https://user-images.githubusercontent.com/7343697/137950366-c3fc48b2-2968-4518-a987-1121e404a5c2.png)

I have a fork that addresses this issue, if you don't mind me opening a pull request? It just specifies which key we want to get from the cookie.

Thanks!

**Comment by bricefrisco** [comment]
Thanks for pointing this out! I hadn't thought about extensions that may add cookies, and coded on the assumption it would be the only one.

I'll review the PR now.
